### PR TITLE
Created composer

### PR DESCRIPTION
**Pull request by uldisn**

### CODE REVIEW

**Comment by sabas** [comment]
Thanks!

**Comment by uldisn** [comment]
You are setup authomerge?

**Comment by sabas** [comment]
I'm at the pc right now :-)

It's better to add this repo as a dependency in the sabas/edifact composer? I splitted in two repos to avoid downloading these xmls each time...

**Comment by uldisn** [comment]
This repository is large and some times my be no required it for sabas/edifact.

**Pull request merged**
